id: P000512
initial_creation_type: ocr
source_metadata:
  id: bdr:W30344
  title: གུ་རུ་དྲག་པོ་རྡོ་རྗེ་གྲོ་ལོད་ཀྱི་ཆོས་སྐོར
  author: ''
  volumes:
    352e37fda0ea4602a5848b37c5ec0e33:
      image_group_id: I1KG5768
      title: Volume 1 of bod kyi deb ther dpyid kyi rgyal mo'i glu dbyangs
      volume_number: 1
      total_pages: 216
ebook_metadata:
  title: གུ་རུ་དྲག་པོ་རྡོ་རྗེ་གྲོ་ལོད་ཀྱི་ཆོས་སྐོར
  author: ''
  sku: P000512
  cover: cover.jpg
  layers:
  - pagination
